{% set name = "cuda-cupti" %}
{% set version = "13.0.48" %}
{% set lib_version = "2025.3.0" %}
{% set cuda_version = "13.0" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set platform = "windows-x86_64" %}  # [win]
{% set target_name = "x86_64-linux" %}  # [linux64]
{% set target_name = "ppc64le-linux" %}  # [ppc64le]
{% set target_name = "sbsa-linux" %}  # [aarch64]
{% set target_name = "x64" %}  # [win]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_cupti/{{ platform }}/cuda_cupti-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: e411ad2f31a9789dcb2c7742ab40cd334f3f1b6176fa3ae1a7958f171dc6b7ae  # [linux64]
  sha256: c1cbc0e042b82df75f54d961da3119da61ed62667eacd911e1c3c9f1ab9bb183  # [aarch64]
  sha256: ce1dd7de1c07151bc027bc2acaee95b16669056b7b788e7ac3ef732cc2f4a007  # [win]

build:
  number: 0
  skip: true  # [osx or ppc64le]

requirements:
  build:
    - cf-nvidia-tools 1.*  # [linux]
    - patchelf <0.18.0  # [linux]

outputs:
  - name: cuda-cupti
    build:
      binary_relocation: false
    files:
      - lib/libcupti*.so.*                    # [linux]
      - targets/{{ target_name }}/lib/*.so.*  # [linux]
      - Library\bin\{{ target_name }}\checkpoint.dll            # [win]
      - Library\bin\{{ target_name }}\cupti*.dll                # [win]
      - Library\bin\{{ target_name }}\nvperf*.dll               # [win]
      - Library\bin\{{ target_name }}\pcsamplingutil.dll        # [win]
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - {{ stdlib("c") }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
      host:
        - cuda-version {{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
    test:
      requires:
        - patchelf  # [linux]
      files:
        - test-rpath.sh
      commands:
        - test -L $PREFIX/lib/libcupti.so.{{ version.split(".")[0] }}                            # [linux]
        - test -L $PREFIX/lib/libcupti.so.{{ lib_version }}                                      # [linux]
        - test -L $PREFIX/targets/{{ target_name }}/lib/libcupti.so.{{ version.split(".")[0] }}  # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/lib/libcupti.so.{{ lib_version }}            # [linux]
        - bash test-rpath.sh                                                                     # [linux]
        - if not exist %LIBRARY_BIN%\{{ target_name }}\checkpoint.dll exit 1                 # [win]
        - if not exist %LIBRARY_BIN%\{{ target_name }}\cupti64_{{ lib_version }}.dll exit 1  # [win]
        - if not exist %LIBRARY_BIN%\{{ target_name }}\nvperf_host.dll exit 1                # [win]
        - if not exist %LIBRARY_BIN%\{{ target_name }}\nvperf_target.dll exit 1              # [win]
        - if not exist %LIBRARY_BIN%\{{ target_name }}\pcsamplingutil.dll exit 1             # [win]
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: Provides libraries to enable third party tools using GPU profiling APIs.
      description: |
        Provides libraries to enable third party tools using GPU profiling APIs.
      doc_url: https://docs.nvidia.com/cuda/cupti/index.html

  - name: cuda-cupti-dev
    build:
      run_exports:
        - {{ pin_subpackage("cuda-cupti", max_pin="x") }}
    files:
      - lib/checkpoint.so                         # [linux]
      - lib/libcupti.so                           # [linux]
      - lib/libnv*.so                             # [linux]
      - lib/libpcsamplingutil.so                  # [linux]
      - targets/{{ target_name }}/lib/*.so        # [linux]
      - targets/{{ target_name }}/include         # [linux]
      - Library\include                           # [win]
      - Library\lib\{{ target_name }}\*.lib       # [win]
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - {{ stdlib("c") }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
      host:
        - cuda-version {{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
        - {{ pin_subpackage("cuda-cupti", exact=True) }}
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - cuda-cupti-static >={{ version }}
    test:
      commands:
        - test -L $PREFIX/lib/libcupti.so                                    # [linux]
        - test -L $PREFIX/lib/libnvperf_host.so                              # [linux]
        - test -L $PREFIX/lib/libnvperf_target.so                            # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/include/cupti.h          # [linux]
        - test -L $PREFIX/targets/{{ target_name }}/lib/libcupti.so          # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/lib/libnvperf_host.so    # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/lib/libnvperf_target.so  # [linux]
        - if not exist %LIBRARY_LIB%\{{ target_name }}\cupti.lib exit 1      # [win]
        - if not exist %LIBRARY_INC%\cupti.h exit 1                          # [win]
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: Provides libraries to enable third party tools using GPU profiling APIs.
      description: |
        Provides libraries to enable third party tools using GPU profiling APIs.
      doc_url: https://docs.nvidia.com/cuda/cupti/index.html

  - name: cuda-cupti-static
    build:
      skip: true  # [not linux64]
    files:
      - targets/{{ target_name }}/lib/*static.a
    requirements:
      build:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
      host:
        - cuda-version {{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
    test:
      commands:
        - test -f $PREFIX/targets/{{ target_name }}/lib/libcupti_static.a  # [linux]
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: Provides libraries to enable third party tools using GPU profiling APIs.
      description: |
        Provides libraries to enable third party tools using GPU profiling APIs.
      doc_url: https://docs.nvidia.com/cuda/cupti/index.html

  - name: cuda-cupti-doc
    files:
      - targets/{{ target_name }}/cuda-cupti/samples
      - targets/{{ target_name }}/cuda-cupti/doc
    requirements:
      build:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
      host:
        - cuda-version {{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
    test:
      commands:
        - test -d $PREFIX/targets/{{ target_name }}/cuda-cupti/samples  # [linux]
        - test -d $PREFIX/targets/{{ target_name }}/cuda-cupti/doc      # [linux]
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: Provides libraries to enable third party tools using GPU profiling APIs.
      description: |
        Provides libraries to enable third party tools using GPU profiling APIs.
      doc_url: https://docs.nvidia.com/cuda/cupti/index.html

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Provides libraries to enable third party tools using GPU profiling APIs.
  description: |
    Provides libraries to enable third party tools using GPU profiling APIs.
  doc_url: https://docs.nvidia.com/cuda/cupti/index.html

extra:
  feedstock-name: cuda-cupti
  recipe-maintainers:
    - conda-forge/cuda
